# workspace:
#   base: /drone/src
#   path: ./
pipeline:
  
  build-master:
    image: 'node:10.6.0'
    commands:
      - 'echo hello'
    when:
      branch: master
  public-online:      
    image: plugins/docker 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    commands:
      - 'docker login --username=hesouli -p Cptbtptp123 registry.cn-beijing.aliyuncs.com'
      - 'docker build --rm -t docker_test_02 .'
      - 'docker tag docker_test_02 registry.cn-beijing.aliyuncs.com/my_docker_test_01/docker_test_02'
      - 'docker push registry.cn-beijing.aliyuncs.com/my_docker_test_01/docker_test_02'
      # - 'docker login --username=hesouli -p Cptbtptp123 registry.cn-beijing.aliyuncs.com'
      # - 'docker build --rm -t one .'
      # - 'docker tag one registry.cn-beijing.aliyuncs.com/panda-docker-test/one'
      # - 'docker push registry.cn-beijing.aliyuncs.com/panda-docker-test/one'
    when: 
      branch: master  
  rancher-online:
    image: peloton/drone-rancher
    url: 'https://rancher.11vx.cn'
    access_key: 7C3B0D6FFBAAF845DD3D
    secret_key: CyVAH7yQbqPCTGMiFxN5oQEZVf53tAAR1LDRn6Bn
    service: my-test-01/test-01 
    docker_image: 'registry.cn-beijing.aliyuncs.com/my_docker_test_01/docker_test_02'
    start_first: false
    confirm: true
    timeout: 300 
    when:
      branch: master 

  